{% set name = "windse" %}
{% set branch = "master" %}
{% set version = "0.8" %}
{% set fenics_version = "2018.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ fenics_version }}_{{ version }}

source:

  url: https://github.com/NREL/WindSE/raw/{{ branch }}/archives/{{ name }}-{{ fenics_version }}_{{ version }}.tar.gz
  sha256: 866322c2c1ab655c3e1436ce18e534b73b3436a30e1f6b2e5d4666c5a19de7f7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - windse = windse_driver.driver:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - fenics {{ fenics_version }}.*
    - dolfin-adjoint {{ fenics_version }}.*
    - scipy
    - mshr 
    - matplotlib
    - pyyaml

test:
  imports:
    - dolfin
    - dolfin_adjoint
    - windse
  commands:
    - windse run --help

about:
  home: https://github.com/NREL/WindSE
  license: Apache 2.0
  license_family: APACHE
  license_file: License.txt
  summary: 'A FEniCS based tool for wind-farm simulations and optimizations.'
  description: |
    Wind Systems Engineering (WindSE) is a simple tool for running RANS based
    simulation of wind farms. It can be used to optimize layouts, yaws, and 
    axial induction. It is developed and maintainered by NREL.
  doc_url: https://windse.readthedocs.io/en/driver/
  dev_url: https://github.com/NREL/WindSE

extra:
  recipe-maintainers:
    - jefalon
