travis:
  secure:
    BINSTAR_TOKEN: oAi80ikfPeSWvXdr8xBLPeLchlEO6DIB5AYfifuWtako4mpj/kg6Fprk873QfENURDCrEDZ3v2emX74z/PrtmOCuMAXA9AcoDyQIsExLh0lyiw9YU1rc3efEJU8q5puIqPz0vGpl71YQdud8YW+fif9pu6kqHX5aTOcDbbkT5V66/fHYuAcn2kweJ+I90XH+dKU89qiJHvwx08ppJjFE1vj/+H8lOMQiV4D4EWUAazPKBA79if7s9KNCjy11IC6I6e1V3hdvgUDGJnU6hYtWG52IIqKoXDGRU8uFqxBx2g61DxyylM7r2XQy70BOenJfPXs2lfaPhu9Ed5uQA2K8QHnGPqEw15ATjESBAdnBdMD1N3vpuw9T/IJiVDcCqUcHeDhao0+aIeRcDBz+zrez/axBb2jG642EIoHt0CRTfAr2H2EcDE2FtcPJw7aupXIZs5rVSgAVjCXyu2rkGVBxvz1Ag97O72oDceSFm2JuPUkOOS/CpE/Yi5x/3QkdXWJhPJss+M6FMBea2tFpP3TzsO7tUlkygBmQE6dFjdxbzEajcaMibhx7bC/4C+yCKAhggSRZ9srnd2lOTS+oLP2J2okklB2mDSdHde6iJnXRR3ffegZWfn5ODSZC1I1WPV7PxbcpzrxrVUFu8EiidsvVuNadV1IrdHd91okVzD7/4YM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
